version: '3'

services:
  redis:
    image: redis
    restart: "no"
    ports:
      - "6379:6379"
  app:
    restart: "no"
    build:
      context: .
      dockerfile: Dockerfile   
    ports:
      - "5000:5000"
    depends_on:
      - redis
    stop_grace_period: 30s

